name: cron job

on:
  workflow_dispatch:
  schedule:
    - cron: "5/6 * * * *" # run at 00:00 AM IST
    
jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Paradox Validate Links
        run: echo "asdf = ${github.event_name}"

    
